[[session]]
name = "ND-Netdaemon ğŸš€"
path = "~/git/netdaemon"
startup_command = "~/.config/sesh/scripts/dev.sh"

[[session]]
name = "ND-Docs ğŸ“ƒ"
path = "~/git/docs"
startup_command = "~/.config/sesh/scripts/dev.sh"

[[session]]
name = "Dotfiles ğŸ–¥ï¸"
path = "~/git/dotfiles"
